participant 판매자 as 판매자
participant 중개자 as 중개자
participant 구매자 as 구매자

alt 중개자 중심시장
    중개자 -> 판매자 : 구매채널 확보 (구매가 공시)
    중개자 -> 구매자 : 판매채널 확보 (판매가 공시)
    판매자 -> 중개자 : 팔래요
    중개자 -> 판매자 : ㅇㅋ 거래성사
    구매자 -> 중개자 : 살래요
    중개자 -> 구매자 : ㅇㅋ 거래성사
end

alt 판매자 중심시장
    판매자 -> 중개자 : **{판매가격}** 에 판매해주세요
    중개자 -> 구매자 : 판매채널 확보 (판매가 제시)
    note right of 중개자
        이때 중개자는 
        - 판매가에 마진을 이미 붙이거나,
        - 구매자 또는 판매자로부터 별도의 수수료를 받음
    end note
    구매자 -> 중개자 : 이거 살래요
    중개자 -> 판매자 : 산다네? 팔거지?
    판매자 -> 중개자 : ㅇㅋ
    중개자 -> 구매자 : ㅇㅋ 거래성사
end

alt 구매자 중심시장
    구매자 -> 중개자 : **{구매가격}** 에 구매해주세요
    중개자 -> 판매자 : 구매채널 확보 (구매가 제시)
    note left of 중개자
        이때 중개자는 
        - 구매가에 마진을 이미 제하거나,
        - 구매자 또는 판매자로부터 별도의 수수료를 받음
    end note
    판매자 -> 중개자 : 이거 팔래요
    중개자 -> 구매자 : 이거 판다네? 살거지?
    구매자 -> 중개자 : ㅇㅋ
    중개자 -> 판매자 : ㅇㅋ 거래성사
end

