
client -> client++ : 실명인증 form UI
[-> client : form submit
client -> ZOO_AUTH++ : **[실명확인 API]** 호출
note right of ZOO_AUTH
    이름
    주민번호 (외국인등록번호)
    내외국인 여부
end note
client -> client++ : 로딩 UI

alt 내외국인 여부 == 내국인
    ZOO_AUTH -> 3RD_PARTY++ : 실명확인 API 호출\n(NICE API)
    return
    alt 실명확인 진위여부 == True
        ZOO_AUTH -> ZOO_DB++ : **"zoo_name_verification"** 테이블 UPSERT
        return
        ZOO_AUTH -> ZOO_DB++ : **"account_certification"** 테이블 UPSERT\n(account_user_id 의 **실명인증** 여부를 True로 UPSERT)
        return
    end
else 내외국인 여부 == 외국인
    ZOO_AUTH -> ZOO_AUTH++ : 외국인등록번호 검증 (알고리즘)
    deactivate ZOO_AUTH

    alt 외국인등록번호 검증 결과 == True
        ZOO_AUTH -> ZOO_DB++ : **"zoo_name_verification"** 테이블 UPSERT
        return
        ZOO_AUTH -> ZOO_DB++ : **"account_certification"** 테이블 UPSERT\n(account_user_id 의 **실명인증** 여부를 True로 UPSERT)
        return
end
end

ZOO_AUTH -> client : **[실명확인 API]** 응답
deactivate
