
client -> client++ : OCR UI
[-> client : OCR 촬영
client -> Google++ : OCR image 전송
return OCR 응답
note left of Google
    이름, 주민번호, 
    면허번호, 기간
end note
deactivate
client -> client++ : 데이터 수정 form UI
[-> client : form submit

client -> ZOO_AUTH++ : **[면허확인 API]** 호출
note left of ZOO_AUTH
    이름
    주민번호
    면허번호
    ...
end note

ZOO_AUTH -> ZOO_DB++ : **[zoo_driver_license(pass 포함)]**(기존 면허) 테이블 조회 
note right of ZOO_AUTH
    본인인증에서 리턴받은 휴대폰번호 기준으로 phone column 에서 검색하여 레코드를 가져온다.
end note
return 찾은 기존 면허의 레코드

alt 레코드가 있다 AND 찾은 레코드의 실명 == 본인인증 실명
    ZOO_AUTH -> ZOO_AUTH : 기존면허 = 있음
else 이외의 경우
    ZOO_AUTH -> ZOO_AUTH : 기존면허 = 없음
end

alt 기존면허 = 있음 이면
    ZOO_AUTH -> ZOO_DB++ : **[zoo_driver_license(pass 포함)]** 테이블 업데이트\n(해당되는 record 에 "account_user_id" column 삽입)
return
end



ZOO_AUTH -> client : 인증완료 리턴
client -> client++ : 로딩 UI
ZOO_AUTH -> 3RD_PARTY++ : 면허확인 API 호출\n(기웅정보통신)
return
alt 면허확인 진위여부 == True
    ZOO_AUTH -> ZOO_DB : **[zoo_driver_license]** 테이블에 INSERT
end
ZOO_AUTH -> client : **[면허확인API]** 리턴
deactivate ZOO_AUTH

client -> ZOO_AUTH++ : **[실명확인 API]** 호출
note left of ZOO_AUTH
    이름
    주민번호
    ...
end note
ZOO_AUTH -> 3RD_PARTY++ : 실명확인 API 호출\n(NICE API)
return
alt 실명확인 진위여부 == True
    ZOO_AUTH -> ZOO_DB : **[zoo_name_verification]** 테이블에 INSERT
end
ZOO_AUTH -> client : **[실명확인API]** 응답
deactivate



alt 모든 인증 성공
    client -> client++ : 성공 UI 노출
    deactivate
else 1개 인증 실패
    client -> client++ : 일부 인증 실패 UI 노출
    deactivate
else 모든 인증 실패
    client -> client++ : 인증 실패 UI 노출
    deactivate
end


