
client -> client++ : 웹뷰 열기
client -> ZOO_AUTH++ : **"본인확인 API"** 호출
return : NICE 본인확인 UI
client -> client++ : NICE 본인확인 UI 열기
client -> NICE++ : 본인확인정보 전송
note right of client
    - 이름
    - 생년월일
    - 성별
    - 휴대폰번호 
    - 문자인증번호
end note
NICE -> ZOO_AUTH++ : **"본인확인 완료 API"** 호출
deactivate NICE
ZOO_AUTH -> ZOO_DB++ : **"account_user"** 테이블 UPSERT\n(CI와 1:1 인 account_user_id 를 할당한다.)
return
ZOO_AUTH -> ZOO_DB++ : **"account_user_detail"** 테이블 UPSERT\n(account_user_id 에 WK_CODE 를 맵핑)
return
ZOO_AUTH -> ZOO_DB++ : **"zoo_phone_verification"** 테이블 UPSERT\n(account_user_id 의 휴대폰 본인인증 정보)
return
ZOO_AUTH -> ZOO_DB++ : **"account_certification"** 테이블 UPSERT\n(account_user_id 의 모든 인증여부 정보중, **본인인증** 여부를 True 로 UPSERT)
return
ZOO_AUTH -> ZOO_DB++ : **"zoo_driver_license"(pass 포함)**(기존 면허) 테이블 조회
note right of ZOO_AUTH
    본인인증에서 리턴받은 휴대폰번호 기준으로 phone column 에서 검색하여 레코드를 가져온다.
end note
return 찾은 기존 면허의 레코드

alt 레코드가 있다 AND 찾은 레코드의 실명 == 본인인증 실명
    ZOO_AUTH -> ZOO_AUTH : **기존면허인증여부** := 있음
else 이외의 경우
    ZOO_AUTH -> ZOO_AUTH : **기존면허인증여부** := 없음
end

alt 기존면허 == 있음 이면
    ZOO_AUTH -> ZOO_DB++ : **"zoo_driver_license"(pass 포함)** 테이블 업데이트\n(해당되는 record 에 "account_user_id" column 삽입)
    return
    ZOO_AUTH -> ZOO_DB++ : **"account_certification"** 테이블 UPSERT\n(account_user_id 의 모든 인증여부 정보중, **면허인증** 여부를 True 로 UPSERT)
    return
end

ZOO_AUTH -> client : 인증완료 리턴
deactivate ZOO_AUTH
deactivate client

note right of client 
    - 인증완료여부
    - 외국인여부
    - **기존면허인증여부** 존재 여부
    - (실패시에만) 실패사유
    - (실명때문에 실패시에만) 본인인증 실명
    - (실명때문에 실패시에만) 기존면허 실명
end note

alt 기존면허인증여부 == True
    client -> client : 면허확인 여부 := True
end

note right of client
    **e.g.,인증상태 정보**
    - 약관동의 여부 = True or False
    - 본인확인 여부 = True or False
    - 면허확인 여부 = True or False
    - 기존면허확인 여부 = True or False
    - 실명확인 여부 = True or False
    - 외국인 여부 = True or False
end note

alt 인증완료여부 == 실패
    alt 실패사유 == 실명불일치
        client -> client : 인증 실패 (사유 : 실명불일치) UI 노출
    else 이외의 실패사유
        client -> client : 인증 실패 (사유 : 실패사유) UI 노출
end

alt 인증완료여부 == 성공 AND 외국인여부 == 외국인
    client -> client : 외국인 경고 모달 UI 노출
end

alt 

